"""
Utility helper functions
"""
import random
import string
from datetime import datetime


def generate_number(prefix, model=None, field_name='number'):
    """Generate sequential number for entities"""
    if model is None:
        # Fallback to old behavior for backward compatibility
        length = field_name if isinstance(field_name, int) else 6
        number_part = ''.join(random.choices(string.digits, k=length))
        timestamp = datetime.now().strftime("%y%m%d")
        
        if prefix:
            return f"{prefix}{timestamp}{number_part}"
        else:
            return f"{timestamp}{number_part}"
    
    # New behavior for database models
    from models import db
    year = datetime.now().strftime('%Y')
    month = datetime.now().strftime('%m')
    
    # Get last number using scalar query to avoid loading full ORM instance
    field = getattr(model, field_name)
    last_number = db.session.query(field).order_by(field.desc()).limit(1).scalar()
    
    if last_number:
        # Extract sequence number
        try:
            seq = int(last_number.split('-')[-1])
            new_seq = seq + 1
        except:
            new_seq = 1
    else:
        new_seq = 1
    
    return f"{prefix}-{year}{month}-{new_seq:05d}"


def generate_code(prefix: str = "", length: int = 8) -> str:
    """
    Generate a unique alphanumeric code
    
    Args:
        prefix: Optional prefix for the code
        length: Length of the random part
    
    Returns:
        Generated code string
    """
    # Generate random alphanumeric part
    random_part = ''.join(random.choices(string.ascii_uppercase + string.digits, k=length))
    
    if prefix:
        return f"{prefix}{random_part}"
    else:
        return random_part


def format_currency(amount: float, currency: str = "IDR") -> str:
    """
    Format currency amount
    
    Args:
        amount: Amount to format
        currency: Currency code (default IDR)
    
    Returns:
        Formatted currency string
    """
    if currency == "IDR":
        return f"Rp {amount:,.0f}"
    else:
        return f"{currency} {amount:,.2f}"


def validate_email(email: str) -> bool:
    """
    Simple email validation
    """
    import re
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    return re.match(pattern, email) is not None


def sanitize_filename(filename: str) -> str:
    """
    Sanitize filename by removing invalid characters
    """
    import re
    # Remove invalid characters
    sanitized = re.sub(r'[<>:"/\\|?*]', '_', filename)
    # Remove multiple underscores
    sanitized = re.sub(r'_+', '_', sanitized)
    return sanitized.strip('_')


def calculate_percentage(part: float, total: float) -> float:
    """
    Calculate percentage safely
    """
    if total == 0:
        return 0.0
    return round((part / total) * 100, 2)


def truncate_string(text: str, max_length: int = 50) -> str:
    """
    Truncate string with ellipsis if too long
    """
    if len(text) <= max_length:
        return text
    return text[:max_length-3] + "..."


def detect_downtime_category(issue_text: str, is_first_entry: bool = False) -> str:
    """
    Auto-detect downtime category from issue description keywords.
    Returns: 'mesin', 'operator', 'material', 'design', 'idle', 'istirahat', or 'others'
    
    AUTO-GENERATED by Keyword Manager GUI - DO NOT EDIT MANUALLY
    Last synced: 2026-07-06 09:51:11
    
    Args:
        issue_text: The downtime reason/issue description
        is_first_entry: Whether this is the first downtime entry (affects 'setting mc/mesin' categorization)
    """
    if not issue_text:
        return 'others'
    
    text_lower = issue_text.lower()
    
    # ISTIRAHAT - break/prayer time (check FIRST - highest priority)
    istirahat_keywords = [
        'break', 'istirahat', 'makan', 'minum', 'shalat', 'sholat', 'solat', 'toilet'
    ]
    for kw in istirahat_keywords:
        if kw in text_lower:
            return 'others'
    
    # IDLE TIME keywords - waiting for materials/resources (check early - high priority)
    idle_keywords = [
        'ambil kain', 'ambil stiker', 'box belum datang', 'box habis', 'buat carton', 'idle', 
        'ingredient habis', 'kain belum datang', 'kain habis', 'karton habis', 'keranjang habis', 
        'label habis', 'lem habis', 'listrik padam', 'menganggur', 'menghabiskan order', 
        'menhabiskan order', 'menunggu kain', 'menunggu mixing', 'menunggu obat', 
        'menunggu packaging', 'menunggu stiker', 'menunggu tinta', 'menyiapkan produk', 
        'mixing belum siap', 'no order', 'nunggu kain', 'nunggu mixing', 'nunggu obat', 
        'nunggu packaging', 'nunggu stiker', 'nunggu tinta', 'obat belum datang', 'obat habis', 
        'operator dialihkan ke mc 7', 'opr dialihkan ke mc 11', 'opr jalan di mc 10', 
        'packaging belum datang', 'packaging habis', 'packing habis', 'persiapan produk', 
        'produk habis ( opr dialihkan ke packing manual )', 'siapkan produk', 'standby', 
        'stiker belum datang', 'stiker habis', 'susun produk', 'tidak ada order', 'tinta habis', 
        'troli habis', 'trolley habis', 'tunggu approval', 'tunggu bahan', 'tunggu bahan kimia', 
        'tunggu box', 'tunggu glove', 'tunggu gloves', 'tunggu hasil qc', 'tunggu ingredient', 
        'tunggu instruksi', 'tunggu kain', 'tunggu karton', 'tunggu keranjang', 'tunggu label', 
        'tunggu lem', 'tunggu material', 'tunggu mixing', 'tunggu obat', 'tunggu order', 
        'tunggu packaging', 'tunggu produk', 'tunggu qc', 'tunggu sarung tangan', 'tunggu stiker', 
        'tunggu temperatur', 'tunggu temperatur stabil', 'tunggu temperature', 
        'tunggu temperature stabil', 'tunggu tinta', 'tunggu troli', 'tunggu trolley', 'waiting for'
    ]
    for kw in idle_keywords:
        if kw in text_lower:
            return 'idle'
    
    # DESIGN keywords - check BEFORE "setting mc" to catch changeover context
    design_keywords = [
        'changeover', 'cleaning', 'desain salah', 'design error', 'ganti', 'ganti karton', 
        'ganti label', 'ganti order', 'ganti packaging', 'ganti produk', 'ganti stiker', 
        'pasang kain', 'pasang packaging', 'pasang stiker', 'pattern salah', 'persiapan produksi', 
        'pola salah', 'prototype', 're packing', 're-pack', 'repack', 'repacking', 'revisi desain', 
        'revisi design', 'sample', 'sanitasi', 'setting dan tunggu temperatur', 
        'setting tunggu temperatur', 'spec salah', 'spesifikasi salah', 'testing design', 'trial', 
        'ukuran salah', 'warmup'
    ]
    for kw in design_keywords:
        if kw in text_lower:
            return 'design'
    
    # SPECIAL CASE: "setting mc/mesin" - depends on position
    if 'setting mc' in text_lower or 'setting mesin' in text_lower:
        return 'design' if is_first_entry else 'mesin'
    
    # OPERATOR keywords
    operator_keywords = [
        'human error', 'keluar jalur (sambungan)', 'kesalahan operator', 'kurang teliti', 'lupa', 
        'operator error', 'salah input', 'salah pasang', 'salah setting', 'salah ukur', 
        'sambungan', 'setting', 'telat', 'tidak fokus'
    ]
    for kw in operator_keywords:
        if kw in text_lower:
            return 'operator'
    
    # MATERIAL/RAW MATERIAL keywords
    material_keywords = [
        'bahan baku', 'bahan cacat', 'bahan habis', 'bahan kurang', 'bahan rusak', 'benang habis', 
        'benang putus', 'kain cacat', 'kain gembos', 'kain rusak', 'kain terlalu tipis', 
        'kain tidak sesuai', 'kain tipis', 'keluar jalur (kain gembos', 
        'keluar jalur (kain terlalu tipis', 'keluar jalur (kain tidak sesuai', 'kualitas kain', 
        'material cacat', 'material habis', 'material kurang', 'material rusak', 'raw material'
    ]
    for kw in material_keywords:
        if kw in text_lower:
            return 'material'
    
    # MESIN keywords - comprehensive machine-related issues
    mesin_keywords = [
        'angin bocor', 'angin drop', 'angin habis', 'bak mesin', 'baut stacking lepas', 'bearing', 
        'belt putus', 'breakdown', 'calibration', 'cartridge inkjet', 'catridge bocor', 
        'compressor', 'control panel error', 'conveyor', 'dosing', 'dossing', 'end seal', 
        'endseal', 'exhaust error', 'exouse error', 'feeding', 'folding', 'ganti sparepart', 
        'guset', 'head inkjet', 'hidrolik', 'home position error', 'hydraulic', 'ink jet', 
        'ink-jet', 'inkjet', 'inkjet error', 'inkjet macet', 'jarum bengkok', 'jarum patah', 
        'kain keluar jalur', 'kain menggulung', 'kalibrasi', 'ke seal', 'keluar jalur', 
        'keluar jalur (bak mesin', 'keseal', 'lebar kain', 'lebar kain tidak maksimal', 'lipatan', 
        'listrik mati', 'maintenance', 'mc pompa obat tanki bocor', 'mc press', 'menggulung', 
        'merge phase error', 'mesin error', 'mesin macet', 'mesin mati', 'mesin rusak', 
        'mesin trouble', 'motor rusak', 'needle', 'overheat', 'overheating', 
        'packaging panjang pendek', 'packaging putus', 'pendorong kain patah', 'penjepit', 
        'perbaikan', 'pisau', 'pneumatic', 'posisi stiker', 'pound', 'power failure', 
        'print error ( printing buram )', 'printer inkjet', 'produk bocor', 'pusher', 
        'rantai lepas', 'relay', 'seal bawah', 'seal bocor', 'seal error ( produk sobek )', 
        'seal melipat', 'seal rapuh', 'seal samping', 'selang', 'sensor', 'setting inkjet', 
        'simetris', 'simetris error', 'sparepart', 'stacker', 'stacking', 'stiker double', 
        'stiker putus', 'suhu', 'tekanan angin', 'temperature', 'tension', 'terseal', 
        'tidak maksimal', 'tidak rapi', 'tidak stabil', 'timbangan error', 'tinta inkjet', 
        'tumpukan', 'vanbelt'
    ]
    for kw in mesin_keywords:
        if kw in text_lower:
            return 'mesin'
    
    # Generic "keluar jalur" without specific cause -> mesin
    if 'keluar jalur' in text_lower:
        return 'mesin'
    
    return 'others'


def get_setting_value(key, default_value):
    """Retrieve system configuration value by key with a default fallback"""
    try:
        from models.settings import SystemSetting
        setting = SystemSetting.query.filter_by(setting_key=key).first()
        if setting:
            value = setting.setting_value
            if setting.data_type == 'boolean':
                return value.lower() in ['true', '1', 'yes']
            elif setting.data_type == 'integer':
                return int(value)
            elif setting.data_type == 'float':
                return float(value)
            return value
    except Exception as e:
        print(f"Error reading setting {key}: {e}")
    return default_value

