"""Add_document_management_tables

Revision ID: 01ae9d9532d8
Revises: a6fce824c57b
Create Date: 2025-11-03 16:43:20.562768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '01ae9d9532d8'
down_revision = 'a6fce824c57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('number_prefix', sa.String(length=20), nullable=True),
    sa.Column('number_format', sa.String(length=100), nullable=True),
    sa.Column('next_sequence', sa.Integer(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('auto_generate', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code')
    )
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('template_structure', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('paper_size', sa.String(length=20), nullable=True),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('margins', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('header_template', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('footer_template', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('available_fields', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('required_fields', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('font_family', sa.String(length=50), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_code')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('document_title', sa.String(length=200), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('document_data', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('excel_path', sa.String(length=500), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('print_count', sa.Integer(), nullable=True),
    sa.Column('last_printed_at', sa.DateTime(), nullable=True),
    sa.Column('printed_by', sa.Integer(), nullable=True),
    sa.Column('signature_fields', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['printed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number')
    )
    op.create_table('document_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('revision_note', sa.Text(), nullable=True),
    sa.Column('previous_data', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('excel_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wip_variances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wip_ledger_id', sa.Integer(), nullable=False),
    sa.Column('variance_type', sa.String(length=50), nullable=False),
    sa.Column('standard_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('variance_breakdown', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('is_favorable', sa.Boolean(), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=True),
    sa.Column('threshold_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('responsible_person', sa.Integer(), nullable=True),
    sa.Column('is_posted_to_gl', sa.Boolean(), nullable=True),
    sa.Column('gl_entry_id', sa.Integer(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('analyzed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyzed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gl_entry_id'], ['accounting_entries.id'], ),
    sa.ForeignKeyConstraint(['responsible_person'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wip_ledger_id'], ['wip_ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wip_variances')
    op.drop_table('document_revisions')
    op.drop_table('document_logs')
    op.drop_table('document_attachments')
    op.drop_table('documents')
    op.drop_table('document_templates')
    op.drop_table('document_categories')
    # ### end Alembic commands ###
