"""add is_cash_bank to accounts

Revision ID: 0b4cc21b6b04
Revises: 3d02f17ad2dd
Create Date: 2026-08-18 03:33:03.172912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4cc21b6b04'
down_revision = '3d02f17ad2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cash_bank', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('is_cash_bank')

    # ### end Alembic commands ###
