"""increase_bom_item_quantity_precision_to_10_decimals

Revision ID: 0d6dc08faee8
Revises: f21bd3e40c36
Create Date: 2025-11-07 14:26:06.244224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6dc08faee8'
down_revision = 'f21bd3e40c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only update BOM items quantity precision
    with op.batch_alter_table('bom_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=False)

    # Skip work_orders changes - table already has data and these columns exist
    # with op.batch_alter_table('work_orders', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False))
    #     batch_op.create_foreign_key('fk_work_orders_production_plan', 'production_plans', ['production_plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip work_orders downgrade
    # with op.batch_alter_table('work_orders', schema=None) as batch_op:
    #     batch_op.drop_constraint('fk_work_orders_production_plan', type_='foreignkey')
    #     batch_op.drop_column('quantity')

    # Only downgrade BOM items
    with op.batch_alter_table('bom_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.NUMERIC(precision=15, scale=4),
               existing_nullable=False)

    # ### end Alembic commands ###
