"""sales forecast matrix - replace SalesForecast with ForecastHeader/ForecastLine/ForecastLineConversion

Revision ID: 15cf848c1849
Revises: f0304ed5e48d
Create Date: 2026-08-24 14:14:11.091030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15cf848c1849'
down_revision = 'f0304ed5e48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('forecast_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_jan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qty_feb', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qty_mar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qty_apr', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qty_mei', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qty_jun', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qty_jul', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qty_agu', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qty_sep', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qty_okt', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qty_nov', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qty_des', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('best_case', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('most_likely', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('worst_case', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('committed', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['forecast_headers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('header_id', 'product_id', name='uq_forecast_line_header_product')
    )
    op.create_table('forecast_line_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('converted_by', sa.Integer(), nullable=False),
    sa.Column('converted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['converted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['forecast_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'month', name='uq_forecast_line_conversion_line_month')
    )
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.drop_constraint('production_plans_sales_forecast_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'forecast_lines', ['sales_forecast_id'], ['id'])

    with op.batch_alter_table('sales_forecasts', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_forecasts_forecast_number')

    op.drop_table('sales_forecasts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('sales_forecasts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('forecast_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('forecast_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('best_case', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('most_likely', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('worst_case', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('committed', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('actual_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('variance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('accuracy_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('required_manpower', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shifts_per_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('confidence_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('methodology', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('converted_to_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='sales_forecasts_approved_by_fkey'),
    sa.ForeignKeyConstraint(['converted_to_order_id'], ['sales_orders.id'], name='sales_forecasts_converted_to_order_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='sales_forecasts_created_by_fkey'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='sales_forecasts_customer_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='sales_forecasts_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sales_forecasts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sales_forecasts_pkey')
    )
    with op.batch_alter_table('sales_forecasts', schema=None) as batch_op:
        batch_op.create_index('ix_sales_forecasts_forecast_number', ['forecast_number'], unique=True)

    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.create_foreign_key('production_plans_sales_forecast_id_fkey', 'sales_forecasts', ['sales_forecast_id'], ['id'])

    op.drop_table('forecast_line_conversions')
    op.drop_table('forecast_lines')
    op.drop_table('forecast_headers')
    # ### end Alembic commands ###
