"""add item-master sync fields to accurate_sync_logs

Revision ID: 1c8a898d9c5d
Revises: 3aa83aa50d11
Create Date: 2026-08-08 08:44:23.346313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8a898d9c5d'
down_revision = '3aa83aa50d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accurate_item_mappings', schema=None) as batch_op:
        batch_op.drop_constraint('accurate_item_mappings_accurate_item_no_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_accurate_item_mappings_accurate_item_no'), ['accurate_item_no'], unique=True)
        batch_op.create_foreign_key(None, 'products', ['smith_product_id'], ['id'])

    with op.batch_alter_table('accurate_sync_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accurate_item_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('accurate_item_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('proposed_target_table', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('proposed_material_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('proposed_category', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('matched_smith_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('matched_smith_table', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('proposed_changes', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_accurate_sync_logs_accurate_item_id'), ['accurate_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accurate_sync_logs_accurate_tx_no'), ['accurate_tx_no'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('accurate_sync_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accurate_sync_logs_accurate_tx_no'))
        batch_op.drop_index(batch_op.f('ix_accurate_sync_logs_accurate_item_id'))
        batch_op.drop_column('proposed_changes')
        batch_op.drop_column('matched_smith_table')
        batch_op.drop_column('matched_smith_id')
        batch_op.drop_column('proposed_category')
        batch_op.drop_column('proposed_material_type')
        batch_op.drop_column('proposed_target_table')
        batch_op.drop_column('accurate_item_name')
        batch_op.drop_column('accurate_item_id')

    with op.batch_alter_table('accurate_item_mappings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_accurate_item_mappings_accurate_item_no'))
        batch_op.create_unique_constraint('accurate_item_mappings_accurate_item_no_key', ['accurate_item_no'])

    # ### end Alembic commands ###
