"""Add_approval_workflow_tables

Revision ID: 1f168128b360
Revises: 39c745d52de4
Create Date: 2025-11-03 16:00:59.901508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '1f168128b360'
down_revision = '39c745d52de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('require_review', sa.Boolean(), nullable=True),
    sa.Column('require_approval', sa.Boolean(), nullable=True),
    sa.Column('allow_reviewer_edit', sa.Boolean(), nullable=True),
    sa.Column('allow_approver_edit', sa.Boolean(), nullable=True),
    sa.Column('reviewer_roles', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('approver_roles', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('auto_create_journal', sa.Boolean(), nullable=True),
    sa.Column('amount_threshold', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_type')
    )
    op.create_table('approval_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('transaction_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('review_changes', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['accounting_entries.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('action_by', sa.Integer(), nullable=False),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changes', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['action_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('lines', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('total_debit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_credit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_of_materials', schema=None) as batch_op:
        batch_op.drop_column('total_cost_per_pack')
        batch_op.drop_column('total_cost_per_batch')

    with op.batch_alter_table('bom_items', schema=None) as batch_op:
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bom_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.NUMERIC(precision=15, scale=4), nullable=True))

    with op.batch_alter_table('bill_of_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost_per_batch', sa.NUMERIC(precision=15, scale=4), nullable=True))
        batch_op.add_column(sa.Column('total_cost_per_pack', sa.NUMERIC(precision=15, scale=4), nullable=True))

    op.drop_table('pending_journal_entries')
    op.drop_table('approval_history')
    op.drop_table('approval_workflows')
    op.drop_table('approval_configurations')
    # ### end Alembic commands ###
