"""rename purchase_invoices and purchase_invoice_items to deprecated (data folded into invoices)

Revision ID: 2bbb48d8e11a
Revises: e7dc98651fb4
Create Date: 2026-08-18 09:22:17.637739

Manually written (not autogenerated) per Bayu's 2026-08-18 decision: the
tables are RENAMED, never dropped, kept as a physical safety net after the
PurchaseInvoice -> Invoice migration was verified end-to-end. Both tables
were empty (0 rows) in production at the time of this migration - see
PURCHASE_INVOICE_MIGRATION_REPORT.md for the full inventory/verification.
"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '2bbb48d8e11a'
down_revision = 'e7dc98651fb4'
branch_labels = None
depends_on = None


def upgrade():
    op.rename_table('purchase_invoice_items', 'purchase_invoice_items_deprecated')
    op.rename_table('purchase_invoices', 'purchase_invoices_deprecated')


def downgrade():
    op.rename_table('purchase_invoices_deprecated', 'purchase_invoices')
    op.rename_table('purchase_invoice_items_deprecated', 'purchase_invoice_items')
