"""Add specifications and maintenance_schedule to machines

Revision ID: 3877dce6f9e6
Revises: 0d6dc08faee8
Create Date: 2025-11-26 13:52:12.431479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3877dce6f9e6'
down_revision = '0d6dc08faee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_schedule', sa.String(length=50), nullable=True))

    # Skip work_orders changes - already exists or has constraint issues
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('maintenance_schedule')
        batch_op.drop_column('specifications')

    # ### end Alembic commands ###
