"""add product new schema with versioning

Revision ID: 39c745d52de4
Revises: 7feca7c77bd3
Create Date: 2025-11-01 18:46:47.520629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c745d52de4'
down_revision = '7feca7c77bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('kode_produk', sa.String(length=50), nullable=False),
    sa.Column('nama_produk', sa.String(length=200), nullable=False),
    sa.Column('gramasi', sa.String(length=20), nullable=True),
    sa.Column('cd', sa.String(length=20), nullable=True),
    sa.Column('md', sa.String(length=20), nullable=True),
    sa.Column('sheet_per_pack', sa.String(length=20), nullable=True),
    sa.Column('pack_per_karton', sa.String(length=20), nullable=True),
    sa.Column('berat_kering', sa.String(length=20), nullable=True),
    sa.Column('ratio', sa.String(length=20), nullable=True),
    sa.Column('ingredient', sa.String(length=20), nullable=True),
    sa.Column('ukuran_batch_vol', sa.String(length=20), nullable=True),
    sa.Column('ukuran_batch_ctn', sa.String(length=20), nullable=True),
    sa.Column('spunlace', sa.String(length=50), nullable=True),
    sa.Column('rayon', sa.String(length=20), nullable=True),
    sa.Column('polyester', sa.String(length=20), nullable=True),
    sa.Column('es', sa.String(length=20), nullable=True),
    sa.Column('slitting_cm', sa.String(length=20), nullable=True),
    sa.Column('lebar_mr_net_cm', sa.String(length=20), nullable=True),
    sa.Column('lebar_mr_gross_cm', sa.String(length=20), nullable=True),
    sa.Column('keterangan_slitting', sa.String(length=100), nullable=True),
    sa.Column('no_mesin_epd', sa.String(length=50), nullable=True),
    sa.Column('speed_epd_pack_menit', sa.String(length=20), nullable=True),
    sa.Column('meter_kain', sa.String(length=20), nullable=True),
    sa.Column('kg_kain', sa.String(length=20), nullable=True),
    sa.Column('kebutuhan_rayon_kg', sa.String(length=20), nullable=True),
    sa.Column('kebutuhan_polyester_kg', sa.String(length=20), nullable=True),
    sa.Column('kebutuhan_es_kg', sa.String(length=20), nullable=True),
    sa.Column('process_produksi', sa.String(length=100), nullable=True),
    sa.Column('kode_jumbo_roll', sa.String(length=50), nullable=True),
    sa.Column('nama_jumbo_roll', sa.String(length=200), nullable=True),
    sa.Column('kode_main_roll', sa.String(length=50), nullable=True),
    sa.Column('nama_main_roll', sa.String(length=200), nullable=True),
    sa.Column('kapasitas_mixing_kg', sa.String(length=20), nullable=True),
    sa.Column('actual_mixing_kg', sa.String(length=20), nullable=True),
    sa.Column('dosing_kg', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products_new', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_new_kode_produk'), ['kode_produk'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_new_nama_produk'), ['nama_produk'], unique=False)

    op.create_table('product_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_fields', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products_new.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_versions')
    with op.batch_alter_table('products_new', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_new_nama_produk'))
        batch_op.drop_index(batch_op.f('ix_products_new_kode_produk'))

    op.drop_table('products_new')
    # ### end Alembic commands ###
