"""add akun_piutang_id to Customer

Revision ID: 3d02f17ad2dd
Revises: 981bc25b0552
Create Date: 2026-08-16 19:32:00.551811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d02f17ad2dd'
down_revision = '981bc25b0552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('akun_piutang_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'accounts', ['akun_piutang_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('akun_piutang_id')

    # ### end Alembic commands ###
