"""add PeriodClose table

Revision ID: 4d8fab0a40f2
Revises: f0fe09c25c1e
Create Date: 2026-08-16 16:00:44.898082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d8fab0a40f2'
down_revision = 'f0fe09c25c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_closes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('depreciation_summary', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_year', 'period_month', name='uq_period_close_year_month')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period_closes')
    # ### end Alembic commands ###
