"""add invoice_id to shipping_orders

Revision ID: 51515692ed97
Revises: 2bbb48d8e11a
Create Date: 2026-08-18 15:21:45.399376

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '51515692ed97'
down_revision = '2bbb48d8e11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also picked up unrelated DROP TABLE for
    # purchase_invoices_deprecated / purchase_invoice_items_deprecated
    # (leftover from a previous session's schema state, not part of this
    # change). Stripped manually so this migration ONLY touches
    # shipping_orders, per project convention (see
    # PURCHASE_INVOICE_MIGRATION_REPORT.md §5).
    with op.batch_alter_table('shipping_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'invoices', ['invoice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipping_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###
