"""add department, category, description to budgets

Revision ID: 55a999b6cdac
Revises: d1aa70c98a75
Create Date: 2026-08-18 08:43:59.623662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a999b6cdac'
down_revision = 'd1aa70c98a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('category')
        batch_op.drop_column('department')

    # ### end Alembic commands ###
