"""add icon_variant column to machine_layout_nodes

Revision ID: 5a97dc3fcd8d
Revises: f3fea1d4386a
Create Date: 2026-08-10 08:58:26.793507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a97dc3fcd8d'
down_revision = 'f3fea1d4386a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('machine_layout_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_variant', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_layout_nodes', schema=None) as batch_op:
        batch_op.drop_column('icon_variant')


    # ### end Alembic commands ###
