"""Create_new_product_schema_with_relationships

Revision ID: 7feca7c77bd3
Revises: 
Create Date: 2025-11-01 18:30:53.527786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7feca7c77bd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_targets')
    op.drop_table('maintenance_work_orders')
    op.drop_table('products_backup')
    op.drop_table('maintenance_metrics')
    op.drop_table('maintenance_alerts')
    op.drop_table('maintenance_analytics')
    op.drop_table('maintenance_schedule_optimization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_schedule_optimization',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('machine_id', sa.INTEGER(), nullable=False),
    sa.Column('current_frequency_days', sa.INTEGER(), nullable=False),
    sa.Column('recommended_frequency_days', sa.INTEGER(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('failure_history_months', sa.INTEGER(), nullable=True),
    sa.Column('cost_benefit_ratio', sa.FLOAT(), nullable=True),
    sa.Column('risk_reduction_percentage', sa.FLOAT(), nullable=True),
    sa.Column('recommendation_reason', sa.TEXT(), nullable=True),
    sa.Column('expected_cost_savings', sa.FLOAT(), nullable=True),
    sa.Column('expected_availability_improvement', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('approved_by', sa.INTEGER(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('implementation_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_analytics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('analysis_date', sa.DATE(), nullable=False),
    sa.Column('analysis_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('total_machines', sa.INTEGER(), nullable=True),
    sa.Column('active_machines', sa.INTEGER(), nullable=True),
    sa.Column('machines_under_maintenance', sa.INTEGER(), nullable=True),
    sa.Column('average_mttr', sa.FLOAT(), nullable=True),
    sa.Column('average_mtbf', sa.FLOAT(), nullable=True),
    sa.Column('overall_availability', sa.FLOAT(), nullable=True),
    sa.Column('total_maintenance_cost', sa.FLOAT(), nullable=True),
    sa.Column('preventive_cost_ratio', sa.FLOAT(), nullable=True),
    sa.Column('cost_per_machine', sa.FLOAT(), nullable=True),
    sa.Column('preventive_percentage', sa.FLOAT(), nullable=True),
    sa.Column('corrective_percentage', sa.FLOAT(), nullable=True),
    sa.Column('emergency_percentage', sa.FLOAT(), nullable=True),
    sa.Column('schedule_compliance', sa.FLOAT(), nullable=True),
    sa.Column('first_time_fix_rate', sa.FLOAT(), nullable=True),
    sa.Column('parts_availability_rate', sa.FLOAT(), nullable=True),
    sa.Column('availability_trend', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost_trend', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mttr_trend', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_alerts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('machine_id', sa.INTEGER(), nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('overdue_days', sa.INTEGER(), nullable=True),
    sa.Column('estimated_cost', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('acknowledged_by', sa.INTEGER(), nullable=True),
    sa.Column('acknowledged_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_by', sa.INTEGER(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('machine_id', sa.INTEGER(), nullable=False),
    sa.Column('metric_date', sa.DATE(), nullable=False),
    sa.Column('mttr_hours', sa.FLOAT(), nullable=True),
    sa.Column('mtbf_hours', sa.FLOAT(), nullable=True),
    sa.Column('planned_uptime_hours', sa.FLOAT(), nullable=True),
    sa.Column('actual_uptime_hours', sa.FLOAT(), nullable=True),
    sa.Column('downtime_hours', sa.FLOAT(), nullable=True),
    sa.Column('availability_percentage', sa.FLOAT(), nullable=True),
    sa.Column('preventive_cost', sa.FLOAT(), nullable=True),
    sa.Column('corrective_cost', sa.FLOAT(), nullable=True),
    sa.Column('total_maintenance_cost', sa.FLOAT(), nullable=True),
    sa.Column('preventive_count', sa.INTEGER(), nullable=True),
    sa.Column('corrective_count', sa.INTEGER(), nullable=True),
    sa.Column('emergency_count', sa.INTEGER(), nullable=True),
    sa.Column('maintenance_efficiency', sa.FLOAT(), nullable=True),
    sa.Column('parts_availability', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_backup',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('code', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('nonwoven_category', sa.TEXT(), nullable=True),
    sa.Column('primary_uom', sa.TEXT(), nullable=True),
    sa.Column('secondary_uom', sa.TEXT(), nullable=True),
    sa.Column('price', sa.NUMERIC(), nullable=True),
    sa.Column('cost', sa.NUMERIC(), nullable=True),
    sa.Column('material_type', sa.TEXT(), nullable=True),
    sa.Column('min_stock_level', sa.NUMERIC(), nullable=True),
    sa.Column('max_stock_level', sa.NUMERIC(), nullable=True),
    sa.Column('reorder_point', sa.NUMERIC(), nullable=True),
    sa.Column('is_active', sa.NUMERIC(), nullable=True),
    sa.Column('is_sellable', sa.NUMERIC(), nullable=True),
    sa.Column('is_purchasable', sa.NUMERIC(), nullable=True),
    sa.Column('is_producible', sa.NUMERIC(), nullable=True),
    sa.Column('lead_time_days', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.NUMERIC(), nullable=True),
    sa.Column('updated_at', sa.NUMERIC(), nullable=True)
    )
    op.create_table('maintenance_work_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('work_order_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('maintenance_record_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('work_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), nullable=False),
    sa.Column('requested_date', sa.DATETIME(), nullable=False),
    sa.Column('scheduled_start', sa.DATETIME(), nullable=True),
    sa.Column('scheduled_end', sa.DATETIME(), nullable=True),
    sa.Column('actual_start', sa.DATETIME(), nullable=True),
    sa.Column('actual_end', sa.DATETIME(), nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), nullable=True),
    sa.Column('assigned_team', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('progress_percentage', sa.FLOAT(), nullable=True),
    sa.Column('estimated_cost', sa.FLOAT(), nullable=True),
    sa.Column('actual_cost', sa.FLOAT(), nullable=True),
    sa.Column('labor_hours_estimated', sa.FLOAT(), nullable=True),
    sa.Column('labor_hours_actual', sa.FLOAT(), nullable=True),
    sa.Column('safety_requirements', sa.TEXT(), nullable=True),
    sa.Column('quality_checks_required', sa.BOOLEAN(), nullable=True),
    sa.Column('quality_check_passed', sa.BOOLEAN(), nullable=True),
    sa.Column('completion_notes', sa.TEXT(), nullable=True),
    sa.Column('customer_satisfaction', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_number')
    )
    op.create_table('maintenance_targets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('machine_id', sa.INTEGER(), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('target_year', sa.INTEGER(), nullable=False),
    sa.Column('target_month', sa.INTEGER(), nullable=True),
    sa.Column('target_availability', sa.FLOAT(), nullable=True),
    sa.Column('target_mttr_hours', sa.FLOAT(), nullable=True),
    sa.Column('target_mtbf_hours', sa.FLOAT(), nullable=True),
    sa.Column('target_maintenance_cost', sa.FLOAT(), nullable=True),
    sa.Column('target_preventive_ratio', sa.FLOAT(), nullable=True),
    sa.Column('target_schedule_compliance', sa.FLOAT(), nullable=True),
    sa.Column('target_first_time_fix', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
