"""add batch scheduling tables (ProductionRecipe, GlobalCalendar, ExceptionCalendar, MachineCalendarOverride, ProductionBatch) and machine_number/production_batch_id fields

Revision ID: 8e6ae835419d
Revises: d4b32b56cfcb
Create Date: 2026-08-22 06:39:15.555160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e6ae835419d'
down_revision = 'd4b32b56cfcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), nullable=False),
    sa.Column('shift_count', sa.Integer(), nullable=False),
    sa.Column('shift_duration_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_of_week')
    )
    op.create_table('exception_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), nullable=False),
    sa.Column('shift_count', sa.Integer(), nullable=True),
    sa.Column('shift_duration_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exception_date')
    )
    op.create_table('machine_calendar_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('override_date', sa.Date(), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), nullable=False),
    sa.Column('shift_count', sa.Integer(), nullable=False),
    sa.Column('shift_duration_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'override_date', name='uq_machine_calendar_override_machine_date')
    )
    op.create_table('production_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('rate_per_hour', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'machine_id', name='uq_production_recipe_product_machine')
    )
    op.create_table('production_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('shift_number', sa.Integer(), nullable=True),
    sa.Column('sequence_in_shift', sa.Integer(), nullable=True),
    sa.Column('planned_qty', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('realized_qty', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('planned_start_datetime', sa.DateTime(), nullable=True),
    sa.Column('planned_end_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_over_capacity_warning', sa.Boolean(), nullable=False),
    sa.Column('spk_document_id', sa.Integer(), nullable=True),
    sa.Column('spk_is_outdated', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['production_recipes.id'], ),
    sa.ForeignKeyConstraint(['spk_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_batches_batch_number'), ['batch_number'], unique=True)

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('shift_productions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'production_batches', ['production_batch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_productions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('production_batch_id')

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('machine_number')

    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_batches_batch_number'))

    op.drop_table('production_batches')
    op.drop_table('production_recipes')
    op.drop_table('machine_calendar_overrides')
    op.drop_table('exception_calendars')
    op.drop_table('global_calendars')
    # ### end Alembic commands ###
