"""make PendingJournalEntry.workflow_id nullable

Revision ID: 981bc25b0552
Revises: 5c6128c0236f
Create Date: 2026-08-16 17:39:51.675085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981bc25b0552'
down_revision = '5c6128c0236f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_journal_entries', schema=None) as batch_op:
        batch_op.alter_column('workflow_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_journal_entries', schema=None) as batch_op:
        batch_op.alter_column('workflow_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
