"""remove redundant index=True from ews_predictions.shift_production_id

Revision ID: 9c5bd19595ae
Revises: 5a97dc3fcd8d
Create Date: 2026-08-10 09:29:49.516311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5bd19595ae'
down_revision = '5a97dc3fcd8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ews_predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_ews_predictions_shift_production_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ews_predictions', schema=None) as batch_op:
        batch_op.create_index('ix_ews_predictions_shift_production_id', ['shift_production_id'], unique=True)

    # ### end Alembic commands ###
