"""Add_WIP_Accounting_tables

Revision ID: a6fce824c57b
Revises: 1f168128b360
Create Date: 2025-11-03 16:17:03.535430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = 'a6fce824c57b'
down_revision = '1f168128b360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cogs_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('sales_order_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_cogs', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gross_margin_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_posted_to_gl', sa.Boolean(), nullable=True),
    sa.Column('gl_entry_id', sa.Integer(), nullable=True),
    sa.Column('posting_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gl_entry_id'], ['accounting_entries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wip_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('work_order_number', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('planned_quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('actual_quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('completed_quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('standard_material_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('standard_labor_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('standard_overhead_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('standard_total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_material_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_labor_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_overhead_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('material_variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('labor_variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('overhead_variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('yield_variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_posted_to_gl', sa.Boolean(), nullable=True),
    sa.Column('gl_posting_date', sa.DateTime(), nullable=True),
    sa.Column('gl_entry_id', sa.Integer(), nullable=True),
    sa.Column('cogm_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cogm_posted', sa.Boolean(), nullable=True),
    sa.Column('cogm_posting_date', sa.DateTime(), nullable=True),
    sa.Column('cogm_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cogm_entry_id'], ['accounting_entries.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gl_entry_id'], ['accounting_entries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cogm_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('transfer_date', sa.DateTime(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('wip_ledger_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_transferred', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total_manufacturing_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('material_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('overhead_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_absorbed', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_posted_to_gl', sa.Boolean(), nullable=True),
    sa.Column('gl_entry_id', sa.Integer(), nullable=True),
    sa.Column('inventory_updated', sa.Boolean(), nullable=True),
    sa.Column('inventory_movement_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gl_entry_id'], ['accounting_entries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['wip_ledger_id'], ['wip_ledger.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_number')
    )
    op.create_table('wip_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wip_ledger_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_number', sa.String(length=50), nullable=True),
    sa.Column('cost_category', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_posted_to_gl', sa.Boolean(), nullable=True),
    sa.Column('gl_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gl_entry_id'], ['accounting_entries.id'], ),
    sa.ForeignKeyConstraint(['wip_ledger_id'], ['wip_ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wip_variances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wip_ledger_id', sa.Integer(), nullable=False),
    sa.Column('variance_type', sa.String(length=50), nullable=False),
    sa.Column('standard_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('variance_breakdown', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('is_favorable', sa.Boolean(), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=True),
    sa.Column('threshold_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('responsible_person', sa.Integer(), nullable=True),
    sa.Column('is_posted_to_gl', sa.Boolean(), nullable=True),
    sa.Column('gl_entry_id', sa.Integer(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('analyzed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyzed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gl_entry_id'], ['accounting_entries.id'], ),
    sa.ForeignKeyConstraint(['responsible_person'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wip_ledger_id'], ['wip_ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wip_variances')
    op.drop_table('wip_transactions')
    op.drop_table('cogm_transfers')
    op.drop_table('wip_ledger')
    op.drop_table('cogs_postings')
    # ### end Alembic commands ###
