"""add production planning

Revision ID: add_production_planning
Revises: add_pack_per_carton
Create Date: 2025-11-06 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_production_planning'
down_revision = 'add_pack_per_carton'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
