"""Add quantity_before and quantity_after to inventory_movements

Revision ID: 20260505_085800_add_quantity_tracking
Revises: 7889c902bbc1
Create Date: 2026-05-05 08:58:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260505_085800_add_quantity_tracking'
down_revision = '7889c902bbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_before', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('quantity_after', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_column('quantity_after')
        batch_op.drop_column('quantity_before')
    # ### end Alembic commands ###
