"""add product changeover table

Revision ID: add_product_changeover
Revises: None
Create Date: 2025-11-06 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_product_changeover'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
