"""bagian2_part2_inventory_adjustment_material_value_flag

Revision ID: ade0a5ce6fd7
Revises: d64b9e9d08f3
Create Date: 2026-08-19 13:56:00.638992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ade0a5ce6fd7'
down_revision = 'd64b9e9d08f3'
branch_labels = None
depends_on = None


def upgrade():
    # NOTE: unrelated autogenerated drift (DROP purchase_invoices_deprecated /
    # purchase_invoice_items_deprecated tables) stripped from this migration -
    # not part of Bagian 2 part 2 scope. Same drift pattern seen and stripped
    # in prior migrations (d64b9e9d08f3 etc); those deprecated tables are left
    # untouched here.
    with op.batch_alter_table('inventory_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inventory_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_value_adjustment', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['id'])
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['id'])
        batch_op.create_check_constraint(
            'check_adjustment_product_or_material',
            '(product_id IS NOT NULL AND material_id IS NULL) OR (product_id IS NULL AND material_id IS NOT NULL)'
        )


def downgrade():
    with op.batch_alter_table('inventory_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint('check_adjustment_product_or_material', type_='check')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_value_adjustment')
        batch_op.drop_column('inventory_id')
        batch_op.drop_column('material_id')
