"""add purchase invoice fields to Invoice model

Revision ID: b0946114d6dc
Revises: 55a999b6cdac
Create Date: 2026-08-18 09:04:42.539529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0946114d6dc'
down_revision = '55a999b6cdac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_amount', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('other_charges', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('supplier_invoice_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('supplier_invoice_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('received_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('posted_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('posted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('internal_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['posted_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['received_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('internal_notes')
        batch_op.drop_column('posted_at')
        batch_op.drop_column('posted_by')
        batch_op.drop_column('received_by')
        batch_op.drop_column('supplier_invoice_date')
        batch_op.drop_column('supplier_invoice_number')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('other_charges')
        batch_op.drop_column('shipping_amount')

    # ### end Alembic commands ###
