"""add wing_x wing_y wing_oee_x to machine_layout_wings

Revision ID: bf229e7a9bed
Revises: de8326d6c2eb
Create Date: 2026-08-09 20:56:52.994806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf229e7a9bed'
down_revision = 'de8326d6c2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('machine_layout_wings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wing_x', sa.Float(), nullable=False, server_default='40'))
        batch_op.add_column(sa.Column('wing_y', sa.Float(), nullable=False, server_default='20'))
        batch_op.add_column(sa.Column('wing_oee_x', sa.Float(), nullable=False, server_default='420'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_layout_wings', schema=None) as batch_op:
        batch_op.drop_column('wing_oee_x')
        batch_op.drop_column('wing_y')
        batch_op.drop_column('wing_x')


    # ### end Alembic commands ###
