"""add akun_hutang_usaha_id to Supplier

Revision ID: c9b7450de96a
Revises: d7157ccdbee9
Create Date: 2026-08-16 10:44:23.048826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9b7450de96a'
down_revision = 'd7157ccdbee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('akun_hutang_usaha_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'accounts', ['akun_hutang_usaha_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('akun_hutang_usaha_id')

    # ### end Alembic commands ###
