"""change payments.bank_account to bank_account_id FK

Revision ID: d1aa70c98a75
Revises: 0b4cc21b6b04
Create Date: 2026-08-18 03:41:21.073518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1aa70c98a75'
down_revision = '0b4cc21b6b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'accounts', ['bank_account_id'], ['id'])
        batch_op.drop_column('bank_account')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bank_account_id')

    # ### end Alembic commands ###
