"""add_sales_forecast_converted_to_order_id

Revision ID: d4b32b56cfcb
Revises: 8164d6781cee
Create Date: 2026-08-21 13:32:14.467164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4b32b56cfcb'
down_revision = '8164d6781cee'
branch_labels = None
depends_on = None


def upgrade():
    # NOTE: unrelated autogenerated drift (DROP purchase_invoices_deprecated /
    # purchase_invoice_items_deprecated tables) stripped from this migration -
    # not part of this change's scope. Same drift pattern seen and stripped
    # in prior migrations.
    with op.batch_alter_table('sales_forecasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('converted_to_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sales_orders', ['converted_to_order_id'], ['id'])


def downgrade():
    with op.batch_alter_table('sales_forecasts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('converted_to_order_id')
