"""warehouse follow the goods bagian1: material_issue columns

Revision ID: d64b9e9d08f3
Revises: 51515692ed97
Create Date: 2026-08-19 10:32:08.570038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd64b9e9d08f3'
down_revision = '51515692ed97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: pre-existing drift (drop of purchase_invoices_deprecated /
    # purchase_invoice_items_deprecated tables) was stripped from this migration —
    # unrelated to Bagian 1 (Warehouse Follow the Goods). See
    # PURCHASE_INVOICE_MIGRATION_REPORT.md for that table's own migration history.
    # This migration only touches material_issues / material_issue_items.
    with op.batch_alter_table('material_issue_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received_quantity', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('receive_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reservation_status', sa.String(length=20), nullable=False))

    with op.batch_alter_table('material_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('production_plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trigger_source', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('received_confirmed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('received_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('work_order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'production_plans', ['production_plan_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['received_confirmed_by'], ['id'])
        batch_op.create_foreign_key(None, 'sales_orders', ['sales_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_issues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('work_order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('received_confirmed_at')
        batch_op.drop_column('received_confirmed_by')
        batch_op.drop_column('trigger_source')
        batch_op.drop_column('production_plan_id')
        batch_op.drop_column('sales_order_id')

    with op.batch_alter_table('material_issue_items', schema=None) as batch_op:
        batch_op.drop_column('reservation_status')
        batch_op.drop_column('receive_note')
        batch_op.drop_column('received_quantity')
    # ### end Alembic commands ###
    # (purchase_invoices_deprecated / purchase_invoice_items_deprecated recreate
    # DDL stripped along with the drop above — unrelated drift, not this migration's concern)
