"""add account preferences system (9-slot products, category/global defaults, sales/purchase/tax/company/inventory account settings, exchange rates)

Revision ID: d7157ccdbee9
Revises: b69207f3ca68
Create Date: 2026-08-15 20:36:54.189196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7157ccdbee9'
down_revision = 'b69207f3ca68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_rates_currency_pair'), ['currency_pair'], unique=False)

    op.create_table('category_account_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('akun_persediaan_id', sa.Integer(), nullable=True),
    sa.Column('akun_penjualan_id', sa.Integer(), nullable=True),
    sa.Column('akun_retur_penjualan_id', sa.Integer(), nullable=True),
    sa.Column('akun_diskon_penjualan_id', sa.Integer(), nullable=True),
    sa.Column('akun_barang_terkirim_id', sa.Integer(), nullable=True),
    sa.Column('akun_hpp_id', sa.Integer(), nullable=True),
    sa.Column('akun_retur_pembelian_id', sa.Integer(), nullable=True),
    sa.Column('akun_beban_id', sa.Integer(), nullable=True),
    sa.Column('akun_pembelian_belum_tertagih_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['akun_barang_terkirim_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_beban_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_diskon_penjualan_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_hpp_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_pembelian_belum_tertagih_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_penjualan_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_persediaan_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_retur_pembelian_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_retur_penjualan_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_account_defaults', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_account_defaults_category_id'), ['category_id'], unique=True)

    op.create_table('company_account_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('akun_ekuitas_id', sa.Integer(), nullable=True),
    sa.Column('akun_laba_ditahan_id', sa.Integer(), nullable=True),
    sa.Column('exchange_rate_refresh_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['akun_ekuitas_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_laba_ditahan_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_account_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_key', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_account_defaults', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_account_defaults_transaction_key'), ['transaction_key'], unique=True)

    op.create_table('inventory_account_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('akun_penyesuaian_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['akun_penyesuaian_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_account_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('akun_selisih_pembelian_id', sa.Integer(), nullable=True),
    sa.Column('akun_perintah_pembayaran_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['akun_perintah_pembayaran_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_selisih_pembelian_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_account_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('akun_uang_muka_pelanggan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['akun_uang_muka_pelanggan_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_account_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('akun_ppn_keluaran_id', sa.Integer(), nullable=True),
    sa.Column('akun_ppn_masukan_id', sa.Integer(), nullable=True),
    sa.Column('akun_pph22_id', sa.Integer(), nullable=True),
    sa.Column('akun_pph23_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['akun_pph22_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_pph23_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_ppn_keluaran_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['akun_ppn_masukan_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('akun_penyesuaian_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'accounts', ['akun_penyesuaian_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('akun_persediaan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('akun_penjualan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('akun_retur_penjualan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('akun_diskon_penjualan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('akun_barang_terkirim_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('akun_hpp_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('akun_retur_pembelian_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('akun_beban_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('akun_pembelian_belum_tertagih_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'accounts', ['akun_diskon_penjualan_id'], ['id'])
        batch_op.create_foreign_key(None, 'accounts', ['akun_beban_id'], ['id'])
        batch_op.create_foreign_key(None, 'accounts', ['akun_retur_pembelian_id'], ['id'])
        batch_op.create_foreign_key(None, 'accounts', ['akun_penjualan_id'], ['id'])
        batch_op.create_foreign_key(None, 'accounts', ['akun_pembelian_belum_tertagih_id'], ['id'])
        batch_op.create_foreign_key(None, 'accounts', ['akun_persediaan_id'], ['id'])
        batch_op.create_foreign_key(None, 'accounts', ['akun_hpp_id'], ['id'])
        batch_op.create_foreign_key(None, 'accounts', ['akun_retur_penjualan_id'], ['id'])
        batch_op.create_foreign_key(None, 'accounts', ['akun_barang_terkirim_id'], ['id'])

    with op.batch_alter_table('warehouse_stock_snapshot_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_stock_snapshot_detail_material_id'), ['material_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_stock_snapshot_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_stock_snapshot_detail_material_id'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('akun_pembelian_belum_tertagih_id')
        batch_op.drop_column('akun_beban_id')
        batch_op.drop_column('akun_retur_pembelian_id')
        batch_op.drop_column('akun_hpp_id')
        batch_op.drop_column('akun_barang_terkirim_id')
        batch_op.drop_column('akun_diskon_penjualan_id')
        batch_op.drop_column('akun_retur_penjualan_id')
        batch_op.drop_column('akun_penjualan_id')
        batch_op.drop_column('akun_persediaan_id')

    with op.batch_alter_table('inventory_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('akun_penyesuaian_id')

    op.drop_table('tax_account_settings')
    op.drop_table('sales_account_settings')
    op.drop_table('purchase_account_settings')
    op.drop_table('inventory_account_settings')
    with op.batch_alter_table('global_account_defaults', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_account_defaults_transaction_key'))

    op.drop_table('global_account_defaults')
    op.drop_table('company_account_settings')
    with op.batch_alter_table('category_account_defaults', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_account_defaults_category_id'))

    op.drop_table('category_account_defaults')
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rates_currency_pair'))

    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
