"""add RecurringPayment and RecurringPaymentTransaction tables

Revision ID: d7bf270b840d
Revises: e400f9f4ac9a
Create Date: 2026-08-16 15:03:49.548343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7bf270b840d'
down_revision = 'e400f9f4ac9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_number', sa.String(length=100), nullable=False),
    sa.Column('recurring_payment_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recurring_payment_id'], ['recurring_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_payment_transactions_payment_date'), ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_payment_transactions_recurring_payment_id'), ['recurring_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_payment_transactions_transaction_number'), ['transaction_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_payment_transactions')
    op.drop_table('recurring_payments')
    # ### end Alembic commands ###
