"""add CustomerDeposit and CustomerDepositUsage tables

Revision ID: e400f9f4ac9a
Revises: c9b7450de96a
Create Date: 2026-08-16 14:39:53.571891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e400f9f4ac9a'
down_revision = 'c9b7450de96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposit_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('deposit_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_used', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_deposits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_deposits_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_deposits_deposit_number'), ['deposit_number'], unique=True)

    op.create_table('customer_deposit_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deposit_id'], ['customer_deposits.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_deposit_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_deposit_usages_deposit_id'), ['deposit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_deposit_usages_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_deposit_usages')
    with op.batch_alter_table('customer_deposits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_deposits_deposit_number'))
        batch_op.drop_index(batch_op.f('ix_customer_deposits_customer_id'))

    op.drop_table('customer_deposits')
    # ### end Alembic commands ###
