"""add PO linkage fields to InvoiceItem, redirect purchase_returns FK to invoices

Revision ID: e7dc98651fb4
Revises: b0946114d6dc
Create Date: 2026-08-18 09:12:50.401735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7dc98651fb4'
down_revision = 'b0946114d6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: purchase_invoices / purchase_invoice_items DROP TABLE statements
    # were auto-generated here (since the ORM classes were removed from
    # models/purchasing.py) but manually stripped out per Bayu's 2026-08-18
    # decision: rename-only, never drop, and only after full end-to-end
    # verification (see step 8 of the migration plan). The tables are left
    # untouched by this migration; renaming to *_deprecated happens in a
    # separate follow-up migration once the new code path is verified.
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('po_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantity_returned', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'purchase_order_items', ['po_item_id'], ['id'])
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['id'])

    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.drop_constraint('purchase_return_items_invoice_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'invoice_items', ['invoice_item_id'], ['id'])

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.drop_constraint('purchase_returns_invoice_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'invoices', ['invoice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('purchase_returns_invoice_id_fkey', 'purchase_invoices', ['invoice_id'], ['id'])

    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('purchase_return_items_invoice_item_id_fkey', 'purchase_invoice_items', ['invoice_item_id'], ['id'])

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('quantity_returned')
        batch_op.drop_column('po_item_id')
        batch_op.drop_column('material_id')
    # purchase_invoices / purchase_invoice_items recreation intentionally
    # omitted - see note in upgrade(), the tables were never dropped.
    # ### end Alembic commands ###
