"""add NumberSequence table

Revision ID: f0fe09c25c1e
Revises: d7bf270b840d
Create Date: 2026-08-16 15:40:33.260828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0fe09c25c1e'
down_revision = 'd7bf270b840d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_key', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('number_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_number_sequences_sequence_key'), ['sequence_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('number_sequences')
    # ### end Alembic commands ###
