"""add bom history and import log tables

Revision ID: f21bd3e40c36
Revises: d64d2dc664d3
Create Date: 2025-11-07 11:15:12.033450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21bd3e40c36'
down_revision = 'd64d2dc664d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('imported_by', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('products_added', sa.Integer(), nullable=True),
    sa.Column('products_updated', sa.Integer(), nullable=True),
    sa.Column('materials_added', sa.Integer(), nullable=True),
    sa.Column('materials_updated', sa.Integer(), nullable=True),
    sa.Column('boms_created', sa.Integer(), nullable=True),
    sa.Column('boms_updated', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('import_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['bill_of_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_production_plans_plan_number')
        batch_op.create_index(batch_op.f('ix_production_plans_plan_number'), ['plan_number'], unique=True)

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False))
        batch_op.create_foreign_key('fk_work_orders_production_plan', 'production_plans', ['production_plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_work_orders_production_plan', type_='foreignkey')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_plans_plan_number'))
        batch_op.create_index('ix_production_plans_plan_number', ['plan_number'], unique=False)

    op.drop_table('bom_history')
    op.drop_table('bom_import_logs')
    # ### end Alembic commands ###
