"""add legacy_converting_machine_id bridge column to machines

Revision ID: f3fea1d4386a
Revises: bf229e7a9bed
Create Date: 2026-08-10 08:33:00.561678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fea1d4386a'
down_revision = 'bf229e7a9bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legacy_converting_machine_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_machines_legacy_converting_machine_id'), ['legacy_converting_machine_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_legacy_converting_machine_id'))
        batch_op.drop_column('legacy_converting_machine_id')


    # ### end Alembic commands ###
