"""Rebuild Print Template Designer schema: TemplateVersion, DocumentTemplate rework, Document.template_version_id

Revision ID: fdb00c05b72e
Revises: d8368702fbe8
Create Date: 2026-08-23 08:24:58.848568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdb00c05b72e'
down_revision = 'd8368702fbe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_template_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('canvas_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('paper_size', sa.String(length=20), nullable=True),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('canvas_width_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('canvas_height_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_template_id'], ['document_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_template_id', 'version_number', name='uq_template_version_number')
    )
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_version_id', sa.Integer(), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_document_templates_document_type'), ['document_type'], unique=False)
        batch_op.create_foreign_key('fk_document_templates_current_version', 'template_versions', ['current_version_id'], ['id'], use_alter=True)
        batch_op.drop_column('orientation')
        batch_op.drop_column('font_size')
        batch_op.drop_column('required_fields')
        batch_op.drop_column('paper_size')
        batch_op.drop_column('font_family')
        batch_op.drop_column('custom_css')
        batch_op.drop_column('footer_template')
        batch_op.drop_column('header_template')
        batch_op.drop_column('available_fields')
        batch_op.drop_column('template_structure')
        batch_op.drop_column('margins')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_version_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('documents_template_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'template_versions', ['template_version_id'], ['id'])
        batch_op.drop_column('template_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('documents_template_id_fkey', 'document_templates', ['template_id'], ['id'])
        batch_op.drop_column('template_version_id')

    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('margins', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('template_structure', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('available_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('header_template', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('footer_template', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custom_css', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('font_family', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('paper_size', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('required_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('font_size', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('orientation', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_document_templates_current_version', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_document_templates_document_type'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('current_version_id')

    op.drop_table('template_versions')
    # ### end Alembic commands ###
